apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: cart-service
  ports:
    - name: http
      port: 5004
      targetPort: 5004
