apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 5002
      targetPort: 5002
