apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5002"
  DB_HOST: cloudmart-postgres.ccnwaycacsuq.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: cloudmart_db
  DB_SSL: "true"
  REDIS_URL: redis://cloudmart-redis.ycv67f.0001.use1.cache.amazonaws.com:6379
