apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: cloudmart_secret_key
  INTERNAL_SERVICE_TOKEN: cloudmart_internal_token
