aws_region              = "us-east-1"
project_name            = "cloudmart"
db_name                 = "cloudmart_db"
db_username             = "postgres"
db_password             = "password123!"
github_actions_role_arn = "arn:aws:iam::506098131053:role/cloudmart-github-actions-oidc-role"
